kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:tap-one-role-binding'
  namspace: tap-one
subjects:
- kind: ServiceAccount
  name: pod-runner
  namespace: tap-one
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:tap-one-cluster-role'
