apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-second
  namespace: tap-one
spec:
 
  config: |-
   {
      "cniVersion": "0.3.1",
      "name": "macvlan-second",
      "type": "ovn-k8s-cni-overlay",
      "topology":"layer2",
      "mtu": 1300,
      "netAttachDefName": "tap-one/macvlan-second"
   }
