apiVersion: v1
kind: Pod
metadata:
      annotations:
        "k8s.v1.cni.cncf.io/networks": '[
          {
            "name": "macvlan-second",
            "ips": ["10.1.1.1/24"]
          }
        ]'
        openshift.io/required-scc: "tap-one-scc"
      labels:
        deployment: multitool-openshift
      namespace: tap-one
      name: pod3
spec:
      node8Selector:
        podnode: network
      serviceAccountName: pod-runner
      containers:
      - image: "wbitt/network-multitool:openshift-extra"
        imagePullPolicy: IfNotPresent
        name: multitool-openshift
        ports:
        - containerPort: 1180
          protocol: TCP
        - containerPort: 11443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
