---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qemu-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: Pod
metadata:
      annotations:
        "k8s.v1.cni.cncf.io/networks": '[
          {
            "name": "macvlan-second",
            "ips": ["10.1.1.3/24"]
          }
        ]'
        openshift.io/required-scc: "tap-one-scc"
      labels:
        deployment: qemu1-pod
      namespace: tap-one
      name: qemu1
spec:
      serviceAccountName: pod-runner
      containers:
      - image: "qemux/qemu-docker"
        imagePullPolicy: IfNotPresent
        name: qemu1-pod
        env:
        - name: BOOT
          value: "https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/x86_64/alpine-virt-3.19.1-x86_64.iso"
        - name: RAM_SIZE
          value: "1G"
        - name: CPU_CORES
          value: "1"
        - name: DISK_SIZE
          value: "16G"
        ports:
        - containerPort: 8006
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /storage
          name: storage
        - mountPath: /dev/kvm
          name: dev-kvm
        - mountPath: /dev/net/tun
          name: dev-tun
      terminationGracePeriodSeconds: 120
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: qemu-pvc
      - hostPath:
          path: /dev/kvm
        name: dev-kvm
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: dev-tun
